### ISSUE TITLE
建议作业deadline之前不要公开AC代码

### ISSUE THREAD

**Issue by Yitong806** [Octcarp/cs102a#1]
注意第二次作业的deadline是22.4.3 23:55。如果提前公开代码，有可能导致不必要的麻烦（如查重等等）。

**Comment by Octcarp** [comment]
多谢学长提醒。git使用得还很生疏，维护等方面还要多多学习。

**Comment by OctCarp** [comment]
> 注意第二次作业的deadline是22.4.3 23:55。如果提前公开代码，有可能导致不必要的麻烦（如查重等等）。 关于作业代码的仓库维护，欢迎参考本人维护了4个学期的仓库：https://github.com/YeeTone/CS102A-Answer/tree/2022Spring

多谢学长提醒。git使用得还很生疏，维护等方面还要多多学习。

**Comment by Yitong806** [comment]
该仓库维护得不错。下学期有意愿来申请学助吗？

**Comment by OctCarp** [comment]
> 该仓库维护得不错。下学期有意愿来申请学助吗？

有考虑过，但是因为自己是零基础学习计算机，所以担心大二之后自己不一定能很好地平衡专业课学习和学助工作。如果感觉能适应学习节奏有余力的话，会倾向于应聘学助的。

**Comment by Yitong806** [comment]
> > 该仓库维护得不错。下学期有意愿来申请学助吗？
> 
> 有考虑过，但是因为自己是零基础学习计算机，所以担心大二之后自己不一定能很好地平衡专业课学习和学助工作。如果感觉能适应学习节奏有余力的话，会倾向于应聘学助的。

如果考虑好了想来的话，可以随时和我联系，我可以帮忙推荐给实验课老师哈哈哈

**Comment by OctCarp** [comment]
> > > 该仓库维护得不错。下学期有意愿来申请学助吗？
> > 
> > 
> > 有考虑过，但是因为自己是零基础学习计算机，所以担心大二之后自己不一定能很好地平衡专业课学习和学助工作。如果感觉能适应学习节奏有余力的话，会倾向于应聘学助的。
> 
> 如果考虑好了想来的话，可以随时和我联系，我可以帮忙推荐给实验课老师哈哈哈

okk
